"""Compatibility exports for FastAPI boundary dependencies.

New code may import the responsibility-specific modules directly. Existing routes
retain this stable facade while the dependency graph is migrated incrementally.
"""

from istari_service.authentication_dependencies import (
    AuthDependency,
    CurrentActor,
    CurrentSession,
    DetachedCurrentActor,
    DetachedCurrentSession,
    IdentityContextDependency,
    actor_from_session,
    auth_service,
    current_session,
    detached_actor_from_session,
    detached_current_session,
    identity_context_service,
)
from istari_service.database_dependencies import (
    AppSettings,
    DatabaseSession,
    LoginPseudonymKey,
    ReadinessDatabaseSession,
    SessionFactoryDependency,
    WorkflowDependency,
    database_session,
    login_pseudonym_key_from_request,
    readiness_database_session,
    session_factory_from_request,
    settings_from_request,
    workflow_from_request,
)
from istari_service.mutation_dependencies import (
    DetachedMutationActor,
    DetachedMutationSession,
    ElevatedMutationActor,
    MutationActor,
    MutationSession,
    StaffActor,
    StaffMutationActor,
    detached_mutation_actor,
    detached_mutation_session,
    elevated_mutation_actor,
    mutation_actor,
    mutation_session,
    staff_actor_from_session,
    staff_mutation_actor,
)

__all__ = [
    "AppSettings",
    "AuthDependency",
    "CurrentActor",
    "CurrentSession",
    "DatabaseSession",
    "DetachedCurrentActor",
    "DetachedCurrentSession",
    "DetachedMutationActor",
    "DetachedMutationSession",
    "ElevatedMutationActor",
    "IdentityContextDependency",
    "LoginPseudonymKey",
    "MutationActor",
    "MutationSession",
    "ReadinessDatabaseSession",
    "SessionFactoryDependency",
    "StaffActor",
    "StaffMutationActor",
    "WorkflowDependency",
    "actor_from_session",
    "auth_service",
    "current_session",
    "database_session",
    "detached_actor_from_session",
    "detached_current_session",
    "detached_mutation_actor",
    "detached_mutation_session",
    "elevated_mutation_actor",
    "identity_context_service",
    "login_pseudonym_key_from_request",
    "mutation_actor",
    "mutation_session",
    "readiness_database_session",
    "session_factory_from_request",
    "settings_from_request",
    "staff_actor_from_session",
    "staff_mutation_actor",
    "workflow_from_request",
]
