"""Persistence-facing domain enums shared by ORM model modules."""

from enum import StrEnum


class UserRole(StrEnum):
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    REQUESTER = "REQUESTER"
    INTAKE_TRIAGE = "INTAKE_TRIAGE"
    SERVICE_COORDINATION = "SERVICE_COORDINATION"
    OPERATIONS_ALLOCATION = "OPERATIONS_ALLOCATION"
    DELIVERY_TEAM_LEAD = "DELIVERY_TEAM_LEAD"
    DELIVERY_SPECIALIST = "DELIVERY_SPECIALIST"
    QUALITY_RELEASE = "QUALITY_RELEASE"


class IdentityContext(StrEnum):
    """The bounded authorisation context selected for one browser session."""

    CUSTOMER = "CUSTOMER"
    STAFF = "STAFF"


class RequestStatus(StrEnum):
    ROUTING_PENDING = "ROUTING_PENDING"
    TRIAGE_REVIEW = "TRIAGE_REVIEW"
    INFORMATION_REQUIRED = "INFORMATION_REQUIRED"
    COORDINATION_REVIEW = "COORDINATION_REVIEW"
    ON_HOLD = "ON_HOLD"
    ALLOCATION_REVIEW = "ALLOCATION_REVIEW"
    DELIVERY_PLANNING = "DELIVERY_PLANNING"
    IN_PROGRESS = "IN_PROGRESS"
    CUSTOMER_INFORMATION_REQUIRED = "CUSTOMER_INFORMATION_REQUIRED"
    LEAD_REVIEW = "LEAD_REVIEW"
    REWORK_REQUIRED = "REWORK_REQUIRED"
    QUALITY_REVIEW = "QUALITY_REVIEW"
    READY_FOR_RELEASE = "READY_FOR_RELEASE"
    COMPLETED = "COMPLETED"
    CLOSED_NOT_PROGRESSED = "CLOSED_NOT_PROGRESSED"
    CANCELLED = "CANCELLED"


class ProductMode(StrEnum):
    LEGACY = "LEGACY"
    MANAGED = "MANAGED"


class WorkflowInstanceStatus(StrEnum):
    START_PENDING = "START_PENDING"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    TERMINATED = "TERMINATED"
    ERROR = "ERROR"


class WorkflowTaskStatus(StrEnum):
    OPEN = "OPEN"
    CLAIM_PENDING = "CLAIM_PENDING"
    CLAIMED = "CLAIMED"
    COMPLETION_PENDING = "COMPLETION_PENDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"


class DeliverableStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    APPROVED = "APPROVED"
    RELEASED = "RELEASED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"
