"""Realistic synthetic request content for the local demo portfolio."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from uuid import uuid4


def request_body(content: dict[str, str], area: str, urgency: str, due_days: int) -> dict[str, object]:
    due = (datetime.now(UTC).date() + timedelta(days=due_days)).isoformat()
    start = (datetime.now(UTC).date() - timedelta(days=45)).isoformat()
    return {
        "submissionKey": str(uuid4()),
        "title": content["title"].format(area=area),
        "description": content["description"].format(area=area),
        "questionToAnswer": content["question"].format(area=area),
        "desiredOutcome": content["outcome"].format(area=area),
        "backgroundContext": content["background"].format(area=area),
        "subjectAreaOrLocation": area,
        "coverageStart": start,
        "coverageEnd": due,
        "customerUrgency": urgency,
        "supportedActivityOrDecision": content["activity"].format(area=area),
        "requiredBy": due,
        "requiredByReason": "The supported decision is scheduled shortly after this date and a late product cannot be considered.",
        "preferredDeliverableType": content["deliverable_type"],
        "successCriteria": content["success"].format(area=area),
        "constraintsOrCaveats": "No known constraints.",
        "supportingInformation": "Relevant records are noted in the background and can be shared on request.",
        "sensitivity": "STANDARD",
        "handlingInstructions": "Standard handling applies.",
    }

# One fictional operating area per delivery team keeps every request distinct.
TEAM_AREAS = {
    "SSG_TEAM": "Halvern Strait",
    "CEDAR_TEAM": "Brenmore Corridor",
    "QUARTZ_TEAM": "Askel Bay",
    "LANTERN_TEAM": "Caldra Uplands",
    "MOSAIC_TEAM": "Verlan Delta",
    "COMPASS_TEAM": "Ostell Reach",
    "EMBER_TEAM": "Dunlow Plateau",
    "ATLAS_TEAM": "Marren Coast",
    "HARBOUR_TEAM": "Skelby Sound",
    "BEACON_TEAM": "Tarnwick Approaches",
    "SLATE_TEAM": "Ferrow Valley",
    "ORCHARD_TEAM": "Lyndale Basin",
    "LUMEN_TEAM": "Croften Moors",
    "NORTHSTAR_TEAM": "Aldgate Passage",
    "COPPER_TEAM": "Wrenfield Flats",
    "ROWAN_TEAM": "Berrow Estuary",
    "VELA_TEAM": "Hartsel Ridge",
    "KEEL_TEAM": "Modan Narrows",
    "FLINT_TEAM": "Pellworth Heath",
    "THISTLE_TEAM": "Garvel Foreland",
    "GRANITE_TEAM": "Ilsted Lowlands",
    "KESTREL_TEAM": "Norbeck Sound",
    "JUNIPER_TEAM": "Tresmere Fens",
    "VALE_TEAM": "Ockley Downs",
    "TIDAL_TEAM": "Sarnholm Isles",
    "GROVE_TEAM": "Withern Gap",
    "PRISM_TEAM": "Eastvale Margin",
}

# Each template is combined with a team's operating area, so titles never repeat.
TEMPLATES = (
    {
        "title": "Maritime movement summary for {area}",
        "description": "Weekly commercial and small-craft traffic through {area} appears to have shifted away from the recognised lanes. We need a structured summary of the pattern over the last quarter, highlighting departures from seasonal norms and any repeated night-time transits.",
        "question": "How has vessel movement through {area} changed against the seasonal baseline, and which changes are operationally significant?",
        "outcome": "A concise summary the duty planning team can use to adjust patrol tasking for the next quarter.",
        "background": "Harbour logs and open reporting for {area} are held on the shared drive. Previous summaries stopped in the spring cycle.",
        "activity": "Quarterly patrol tasking review for the {area} sector.",
        "deliverable_type": "Written report",
        "success": "Planners can point to the three most significant pattern changes with supporting evidence.",
        "product_title": "{area} maritime movement summary",
        "product_text": "The quarterly review of movement through {area} identifies three sustained departures from the seasonal baseline: a westward shift of bulk-carrier transits, a doubling of night-time small-craft crossings, and reduced use of the recognised inshore lane. Recommended adjustments to patrol tasking are set out in section four.",
    },
    {
        "title": "Port infrastructure condition assessment, {area}",
        "description": "Recent storm damage reports suggest the main cargo berths serving {area} may be operating below stated capacity. Assess current berth condition, crane availability and known repair timelines.",
        "question": "What cargo handling capacity is realistically available at the ports serving {area} over the next six months?",
        "outcome": "A capacity figure per berth with confidence levels, suitable for contingency planning.",
        "background": "Engineering surveys from the operator are partially available. Two berths were closed for inspection last month.",
        "activity": "Regional resupply contingency planning.",
        "deliverable_type": "Data summary",
        "success": "Each berth has a stated usable capacity, a confidence rating and a repair outlook.",
        "product_title": "{area} port capacity assessment",
        "product_text": "Berth-by-berth assessment for {area}: berths one and three are serviceable at full rated capacity; berth two is restricted to lighter traffic pending crane repairs expected to complete within nine weeks. Aggregate handling capacity for the next two quarters is assessed at seventy-eight per cent of the published figure.",
    },
    {
        "title": "Flood impact outlook for supply routes near {area}",
        "description": "Seasonal flooding regularly closes low-lying routes around {area}. Produce an outlook for the coming wet season identifying the routes most likely to close, expected closure duration and viable alternatives.",
        "question": "Which supply routes around {area} are most likely to be lost to flooding this season and for how long?",
        "outcome": "A prioritised list of at-risk routes with recommended alternatives.",
        "background": "Ten years of closure records exist for the region. Two new embankment schemes completed this year are untested.",
        "activity": "Seasonal route planning for regional distribution.",
        "deliverable_type": "Briefing note",
        "success": "Distribution planners can pre-position stock before the highest-risk closures.",
        "product_title": "{area} seasonal flood route outlook",
        "product_text": "Analysis of a decade of closure records around {area} indicates the southern causeway and the river road carry the highest closure risk, with expected outages of three and two weeks respectively. The new eastern embankment is assessed as likely to hold, keeping the upland route open as the primary alternative.",
    },
    {
        "title": "Communications resilience overview, {area}",
        "description": "The fixed and mobile communications serving {area} depend on a small number of shared masts and one undersea link. Summarise single points of failure and realistic outage scenarios.",
        "question": "Where are the single points of failure in communications coverage for {area}?",
        "outcome": "A resilience overview with a ranked list of failure points and mitigation options.",
        "background": "Operator coverage maps are available. The undersea link had two unplanned outages last year.",
        "activity": "Continuity planning for regional operations.",
        "deliverable_type": "Written report",
        "success": "Each failure point has an outage scenario and at least one mitigation.",
        "product_title": "{area} communications resilience overview",
        "product_text": "Coverage for {area} routes through four shared masts and a single undersea link. Loss of the Kelder mast alone would remove service from a third of the sector. Mitigations, including a portable relay plan and priority restoration agreement, are ranked in section three.",
    },
    {
        "title": "Airfield serviceability review, {area}",
        "description": "Confirm the current serviceability of the two airstrips supporting {area}, including surface condition, lighting, fuel availability and any load restrictions in force.",
        "question": "Which aircraft types can each strip supporting {area} accept today, and under what restrictions?",
        "outcome": "A serviceability statement per strip that the movements team can rely on.",
        "background": "The northern strip was resurfaced last year. Fuel deliveries to the southern strip have been irregular.",
        "activity": "Air movement scheduling for the coming quarter.",
        "deliverable_type": "Data summary",
        "success": "Movements can schedule without a further site visit.",
        "product_title": "{area} airfield serviceability statement",
        "product_text": "The northern strip supporting {area} is serviceable day and night for medium transport types with no restrictions. The southern strip is restricted to daylight operations and light types until the lighting fault is cleared and fuel stocks are re-established, expected within six weeks.",
    },
    {
        "title": "Cross-border freight disruption brief, {area}",
        "description": "New inspection arrangements at the crossings serving {area} have lengthened queues. Assess current delay patterns, their causes and the outlook for the next two quarters.",
        "question": "How long are freight delays at the {area} crossings, and are they improving or worsening?",
        "outcome": "A short brief with delay trends and a two-quarter outlook.",
        "background": "Queue-time data is published weekly by the crossing authority. Anecdotal reports conflict with the official figures.",
        "activity": "Procurement lead-time planning.",
        "deliverable_type": "Briefing note",
        "success": "The brief reconciles official and observed delay figures with a clear trend call.",
        "product_title": "{area} crossing delay brief",
        "product_text": "Observed queue times at the {area} crossings average nine hours against the officially published four. The gap is driven by staggered inspection staffing rather than volume. Delays are assessed as likely to shorten modestly next quarter as the second inspection lane opens.",
    },
    {
        "title": "Power grid vulnerability summary for {area}",
        "description": "Summarise the dependency of essential services around {area} on the regional grid, identifying substations whose loss would have the widest effect and the state of backup generation.",
        "question": "Which grid nodes serving {area} matter most, and how ready is backup generation?",
        "outcome": "A ranked node list with backup readiness noted for each essential service.",
        "background": "The regional operator shared a network diagram this spring. Backup generator test records are incomplete.",
        "activity": "Essential services continuity review.",
        "deliverable_type": "Written report",
        "success": "The three highest-impact nodes are identified with mitigation status.",
        "product_title": "{area} grid dependency summary",
        "product_text": "Essential services around {area} draw on eleven substations, of which the Marfield and Denholt nodes carry the widest dependency. Backup generation covers the hospital and water plant, though test records lapse at two smaller sites. Recommended assurance checks are listed in the annexe.",
    },
    {
        "title": "Humanitarian access constraints briefing, {area}",
        "description": "Relief deliveries into {area} face changing checkpoint requirements and road damage. Provide a current picture of access constraints and how they have changed since the spring assessment.",
        "question": "What constraints currently limit relief access into {area} and which have changed since spring?",
        "outcome": "An access picture that convoy planners can use for the next delivery cycle.",
        "background": "The spring assessment is on file. Partner organisations report new checkpoint paperwork requirements.",
        "activity": "Relief convoy planning for the next cycle.",
        "deliverable_type": "Briefing note",
        "success": "Convoy planners can select routes without further enquiries.",
        "product_title": "{area} access constraints briefing",
        "product_text": "Access into {area} has tightened since spring: two checkpoints now require pre-notified manifests and the river bridge remains weight-restricted. The northern approach stays the most reliable, with a documented paperwork pack now essential for all routes. Details and contact points are annexed.",
    },
    {
        "title": "Supply route risk profile, {area}",
        "description": "Build a risk profile for the main supply route through {area} covering road condition, seasonal weather exposure, fuel points and known pinch points.",
        "question": "What are the principal risks to sustained use of the main supply route through {area}?",
        "outcome": "A risk register for the route with likelihood, impact and mitigations.",
        "background": "The route was last profiled two years ago. A new bypass opened in the interim.",
        "activity": "Sustainment planning for forward sites.",
        "deliverable_type": "Written report",
        "success": "Each risk carries an owner and a practical mitigation.",
        "product_title": "{area} supply route risk profile",
        "product_text": "The refreshed profile for the {area} route registers nine risks. The highest-rated are the single-span river crossing and winter closure of the high pass, both mitigated by the new bypass at moderate additional distance. Fuel coverage is adequate except on the final third of the route.",
    },
    {
        "title": "Population movement trend summary, {area}",
        "description": "Local authorities report renewed movement of people through {area} towards the coast. Summarise the scale, routes and likely drivers of the trend over the past two quarters.",
        "question": "What is the scale and direction of population movement through {area}, and what is driving it?",
        "outcome": "A trend summary with figures the regional planning group can cite.",
        "background": "Registration data from three districts is available, with gaps in the northern district.",
        "activity": "Regional reception and support planning.",
        "deliverable_type": "Data summary",
        "success": "The summary gives a defensible range for weekly movement with stated assumptions.",
        "product_title": "{area} movement trend summary",
        "product_text": "Movement through {area} is assessed at four to six hundred people weekly, concentrated on the coastal road and rail line, roughly double the spring rate. The rise correlates with the closure of inland employment schemes. Northern district figures are modelled owing to the registration gap and are flagged accordingly.",
    },
    {
        "title": "Cyber exposure review for services in {area}",
        "description": "Review the exposure of council and utility online services in {area} following the recent phishing campaign reported by the regional response team, and summarise remediation progress.",
        "question": "How exposed are the {area} public services after the recent phishing campaign, and is remediation on track?",
        "outcome": "An exposure summary with a remediation scorecard.",
        "background": "The response team shared indicators last month. Patch status for two utilities is unverified.",
        "activity": "Regional cyber assurance reporting.",
        "deliverable_type": "Written report",
        "success": "Every service has an exposure rating and a remediation status.",
        "product_title": "{area} cyber exposure review",
        "product_text": "Of the fourteen public-facing services reviewed in {area}, eleven completed remediation within the response team's window. The water utility portal and one council payment service remain exposed pending vendor patches, with compensating controls now in place. A thirty-day re-check is recommended.",
    },
    {
        "title": "Bridge and crossing capacity survey, {area}",
        "description": "Survey the load ratings and current condition of the bridges and crossings that carry the two principal roads through {area}, noting any restrictions that would affect heavy movements.",
        "question": "Which crossings in {area} can carry heavy loads today, and where are the binding restrictions?",
        "outcome": "A crossing-by-crossing capacity table for movement planners.",
        "background": "The highways register is current to last year. Two structures were flagged for inspection after the winter.",
        "activity": "Heavy movement route clearance.",
        "deliverable_type": "Data summary",
        "success": "Planners can clear a heavy movement without commissioning a new survey.",
        "product_title": "{area} crossing capacity survey",
        "product_text": "Twelve structures carry the principal roads through {area}. Ten are cleared for heavy movements without restriction. The Ferris viaduct is limited to single-vehicle passage and the old town bridge remains closed to anything above light traffic. Alternative alignments for both are provided.",
    },
    {
        "title": "Severe weather contingency outlook, {area}",
        "description": "Produce a contingency outlook for {area} covering the storm season: expected disruption windows, the services most at risk and the readiness of local response arrangements.",
        "question": "What disruption should be planned for in {area} this storm season and how ready are local arrangements?",
        "outcome": "A contingency outlook the resilience forum can adopt at its next meeting.",
        "background": "Last season saw two major outages. The mutual-aid agreement was revised in the summer.",
        "activity": "Seasonal resilience forum planning.",
        "deliverable_type": "Briefing note",
        "success": "The forum can agree pre-season actions directly from the outlook.",
        "product_title": "{area} storm season outlook",
        "product_text": "The outlook for {area} anticipates two to four disruptive events, with exposed ferry services and the coastal power feed most at risk. Local arrangements are materially stronger than last season following the revised mutual-aid agreement, though generator refuelling remains the weakest link. Five pre-season actions are proposed.",
    },
    {
        "title": "Fuel distribution bottleneck analysis, {area}",
        "description": "Fuel deliveries across {area} have slipped against schedule for two months. Analyse the distribution chain from the terminal to retail and site tanks to locate the binding constraint.",
        "question": "Where is the binding constraint in the {area} fuel distribution chain?",
        "outcome": "A clear statement of the constraint with options to relieve it.",
        "background": "Terminal throughput data and haulier schedules are available for the past year.",
        "activity": "Regional fuel resilience decision.",
        "deliverable_type": "Written report",
        "success": "The named constraint is supported by data and at least two relief options are costed.",
        "product_title": "{area} fuel distribution analysis",
        "product_text": "The constraint in the {area} chain is driver availability on the terminal-to-depot leg, not terminal throughput as previously assumed. Two relief options are assessed: a night-loading window at the terminal, and a short-term third-party haulage contract. Either restores schedule adherence within a month.",
    },
    {
        "title": "Rail corridor condition brief, {area}",
        "description": "Brief on the condition and effective capacity of the freight rail corridor through {area}, including the passing loops, gauge limits and the state of the junction works.",
        "question": "What freight volume can the {area} rail corridor realistically carry over the next year?",
        "outcome": "A capacity statement with the constraints ranked by effect.",
        "background": "The infrastructure owner publishes a capacity statement that predates the junction works.",
        "activity": "Modal shift assessment for regional freight.",
        "deliverable_type": "Briefing note",
        "success": "The brief gives a usable trains-per-day figure with stated assumptions.",
        "product_title": "{area} rail corridor brief",
        "product_text": "The corridor through {area} can support eleven freight paths daily once the junction works complete next quarter, up from eight today. The binding constraints thereafter are the two short passing loops north of the junction. Loop extension would raise capacity to fourteen paths but needs a two-season possession plan.",
    },
)

FEEDBACK_COMMENTS = (
    "Clear, well-structured product delivered ahead of the date we needed it. The summary table was immediately usable.",
    "Good work overall. The evidence base was strong, though we would have valued an earlier interim update.",
    "Exactly what the planning group needed, and the recommendations section saved us a follow-up request.",
    "Thorough and readable. The confidence ratings against each finding were particularly helpful.",
)

CLARIFICATION_REASONS = (
    "The coverage period spans two reporting cycles. Confirm whether the earlier cycle should be included in the baseline.",
    "Two districts share this name in the regional gazetteer. Confirm which district boundary applies to this request.",
)

CLARIFICATION_ANSWERS = (
    "Use both reporting cycles for the baseline; the earlier cycle contains the last complete seasonal picture.",
    "Apply the coastal district boundary as published in this year's gazetteer revision.",
)
