import type {
  StatisticsEvolution,
  StatisticsEvolutionFilters,
} from "../../lib/api/statisticsEvolutionTypes";

export const filters: StatisticsEvolutionFilters = {
  scopeId: "platform",
  unitId: "00000000-0000-4000-8000-000000000001",
  from: "2026-08-01",
  to: "2026-08-07",
  timeZone: "Europe/London",
};

export const evolution: StatisticsEvolution = {
  scope: {
    id: "platform",
    unitId: filters.unitId,
    name: "Whole platform",
    kind: "PLATFORM",
    includeDescendants: true,
    units: [{ id: filters.unitId, parentId: null, name: "CRIOC", kind: "ROOT", depth: 0 }],
  },
  selectedUnit: { id: filters.unitId, parentId: null, name: "CRIOC", kind: "ROOT", depth: 0 },
  breadcrumb: [{ id: filters.unitId, parentId: null, name: "CRIOC", kind: "ROOT", depth: 0 }],
  range: {
    fromDate: filters.from,
    toDate: filters.to,
    timeZone: filters.timeZone,
    asOfDate: filters.to,
  },
  freshness: {
    health: "READY",
    lastProjectedAt: "2026-08-07T10:30:00Z",
    sourceEventCount: 42,
    projectedRequestCount: 18,
  },
  comparison: [
    {
      key: "received",
      label: "Received",
      current: 12,
      previous: 8,
      change: 4,
      unit: "count",
      suppressed: false,
    },
    {
      key: "completion",
      label: "Completion",
      current: 75,
      previous: 80,
      change: -5,
      unit: "percentage",
      suppressed: false,
    },
    {
      key: "duration",
      label: "Lead time",
      current: 14,
      previous: 15,
      change: -1,
      unit: "hours",
      suppressed: false,
    },
    {
      key: "unavailable",
      label: "Unavailable comparison",
      current: null,
      previous: null,
      change: null,
      unit: "count",
      suppressed: false,
    },
    {
      key: "stable",
      label: "Stable demand",
      current: 5,
      previous: 4,
      change: 1,
      unit: "count",
      suppressed: false,
    },
    {
      key: "small",
      label: "Small cohort",
      current: null,
      previous: null,
      change: null,
      unit: "count",
      suppressed: true,
    },
  ],
  bottlenecks: [
    {
      key: "manager",
      label: "Manager review",
      activeCount: 4,
      medianAgeHours: 8,
      p90AgeHours: 26,
      overdueCount: 1,
      suppressed: false,
    },
    {
      key: "quality",
      label: "Quality review",
      activeCount: 2,
      medianAgeHours: 4,
      p90AgeHours: 12,
      overdueCount: 0,
      suppressed: false,
    },
    {
      key: "allocation",
      label: "Team allocation",
      activeCount: 3,
      medianAgeHours: 9,
      p90AgeHours: 30,
      overdueCount: 1,
      suppressed: false,
    },
    {
      key: "unavailable",
      label: "Unavailable stage",
      activeCount: null,
      medianAgeHours: null,
      p90AgeHours: null,
      overdueCount: null,
      suppressed: false,
    },
  ],
  capacity: [
    {
      date: "2026-08-06",
      availableMinutes: 1_200,
      reservedMinutes: 240,
      activeWorkMinutes: 600,
      projectedDemandMinutes: 900,
      estimate: true,
    },
    {
      date: "2026-08-07",
      availableMinutes: 1_080,
      reservedMinutes: 180,
      activeWorkMinutes: 540,
      projectedDemandMinutes: 780,
      estimate: false,
    },
  ],
  releases: [
    { key: "released", label: "Products released", count: 5, medianHours: 18, suppressed: false },
    { key: "replaced", label: "Products replaced", count: 1, medianHours: null, suppressed: false },
    {
      key: "unavailable",
      label: "Unavailable release",
      count: null,
      medianHours: null,
      suppressed: false,
    },
  ],
  notifications: [
    {
      key: "routing",
      label: "Routing actions",
      count: 9,
      medianResponseHours: 2,
      unresolvedCount: 2,
      suppressed: false,
    },
    {
      key: "release",
      label: "Release actions",
      count: 4,
      medianResponseHours: null,
      unresolvedCount: 1,
      suppressed: false,
    },
    {
      key: "unavailable",
      label: "Unavailable actions",
      count: null,
      medianResponseHours: null,
      unresolvedCount: null,
      suppressed: false,
    },
  ],
  iterations: [
    {
      key: "pilot",
      label: "Pilot iteration",
      committedCount: 8,
      completedCount: 6,
      completionPercentage: 75,
      suppressed: false,
    },
    {
      key: "new",
      label: "New iteration",
      committedCount: 0,
      completedCount: 0,
      completionPercentage: null,
      suppressed: false,
    },
    {
      key: "unavailable",
      label: "Unavailable iteration",
      committedCount: null,
      completedCount: null,
      completionPercentage: null,
      suppressed: false,
    },
  ],
  projection: {
    label: "Deterministic estimate from authorised aggregate facts",
    estimate: true,
    periods: [
      { date: "2026-08-08", demandCount: 10, capacityCount: 8 },
      { date: "2026-08-09", demandCount: 6, capacityCount: 7 },
    ],
  },
  exports: {
    csv: { state: "AVAILABLE", reason: "Aggregate cohort is large enough." },
    pdf: { state: "DENIED", reason: "PDF export is not granted for this scope." },
  },
};
