"""initial relational schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-06 17:24:17.275901
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "PLATFORM_ADMIN",
                "REQUESTER",
                "INTAKE_TRIAGE",
                "SERVICE_COORDINATION",
                "OPERATIONS_ALLOCATION",
                "DELIVERY_TEAM_LEAD",
                "DELIVERY_SPECIALIST",
                "QUALITY_RELEASE",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False
        ),
        sa.Column(
            "failed_login_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "credential_version", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "organisation_units",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "ROOT",
                "COMMAND",
                "OPS_GROUP",
                "TEAM",
                name="organisation_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "staffing_status",
            sa.Enum(
                "ROUTING_POOL",
                "STAFFED",
                "UNSTAFFED",
                name="staffing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("routing_candidate_group", sa.String(length=120), nullable=True),
        sa.Column("manager_candidate_group", sa.String(length=120), nullable=True),
        sa.Column("analyst_candidate_group", sa.String(length=120), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "is_configured",
            sa.Boolean(),
            server_default=sa.text("(true)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'ROOT' AND parent_id IS NULL) OR "
            "(kind <> 'ROOT' AND parent_id IS NOT NULL)",
            name=op.f("ck_organisation_units_organisation_parent_shape"),
        ),
        sa.CheckConstraint(
            "(kind = 'TEAM' AND staffing_status IN ('STAFFED', 'UNSTAFFED')) OR "
            "(kind <> 'TEAM' AND staffing_status = 'ROUTING_POOL')",
            name=op.f("ck_organisation_units_organisation_staffing_shape"),
        ),
        sa.CheckConstraint(
            "(kind = 'TEAM' AND routing_candidate_group IS NULL "
            "AND manager_candidate_group IS NOT NULL "
            "AND analyst_candidate_group IS NOT NULL) OR "
            "(kind <> 'TEAM' AND routing_candidate_group IS NOT NULL "
            "AND manager_candidate_group IS NULL "
            "AND analyst_candidate_group IS NULL)",
            name=op.f("ck_organisation_units_organisation_candidate_group_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organisation_units.id"],
            name=op.f("fk_organisation_units_parent_id_organisation_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation_units")),
    )
    with op.batch_alter_table("organisation_units", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organisation_units_code"), ["code"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_organisation_units_is_configured"),
            ["is_configured"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organisation_units_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organisation_units_parent_id"),
            ["parent_id"],
            unique=False,
        )

    op.create_table(
        "service_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("service_category", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("desired_outcome", sa.Text(), nullable=False),
        sa.Column("background_context", sa.Text(), nullable=False),
        sa.Column("required_by", sa.Date(), nullable=False),
        sa.Column("required_by_reason", sa.Text(), nullable=False),
        sa.Column("preferred_deliverable_type", sa.String(length=80), nullable=False),
        sa.Column("success_criteria", sa.Text(), nullable=False),
        sa.Column("requesting_business_area", sa.String(length=120), nullable=False),
        sa.Column("intended_recipients", sa.JSON(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("handling_instructions", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ROUTING_PENDING",
                "TRIAGE_REVIEW",
                "INFORMATION_REQUIRED",
                "COORDINATION_REVIEW",
                "ON_HOLD",
                "ALLOCATION_REVIEW",
                "DELIVERY_PLANNING",
                "IN_PROGRESS",
                "LEAD_REVIEW",
                "REWORK_REQUIRED",
                "QUALITY_REVIEW",
                "READY_FOR_RELEASE",
                "COMPLETED",
                "CLOSED_NOT_PROGRESSED",
                "CANCELLED",
                name="request_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="ROUTING_PENDING",
            nullable=False,
        ),
        sa.Column("current_owner", sa.String(length=120), nullable=False),
        sa.Column("triage_category", sa.String(length=80), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("assigned_delivery_team", sa.String(length=80), nullable=True),
        sa.Column("assigned_specialist_id", sa.Uuid(), nullable=True),
        sa.Column("command_group", sa.String(length=120), nullable=True),
        sa.Column("ops_group", sa.String(length=120), nullable=True),
        sa.Column("team_manager_group", sa.String(length=120), nullable=True),
        sa.Column("team_analyst_group", sa.String(length=120), nullable=True),
        sa.Column(
            "awaiting_team_staffing",
            sa.Boolean(),
            server_default=sa.text("(false)"),
            nullable=False,
        ),
        sa.Column("required_capabilities", sa.JSON(), nullable=True),
        sa.Column("workflow_error", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "audit_event_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("audit_head_hash", sa.String(length=64), nullable=True),
        sa.Column("audit_anchor_mac", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_specialist_id"],
            ["users.id"],
            name=op.f("fk_service_requests_assigned_specialist_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_service_requests_requester_id_users"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "(audit_event_count = 0 AND audit_head_hash IS NULL "
            "AND audit_anchor_mac IS NULL) OR "
            "(audit_event_count > 0 AND audit_head_hash IS NOT NULL "
            "AND audit_anchor_mac IS NOT NULL)",
            name=op.f("ck_service_requests_audit_anchor_consistency"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_requests")),
    )
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_requests_assigned_delivery_team"),
            ["assigned_delivery_team"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_assigned_specialist_id"),
            ["assigned_specialist_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_reference"), ["reference"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_requester_id"),
            ["requester_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_service_requests_status"), ["status"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_organisation_memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["organisation_units.id"],
            name=op.f("fk_user_organisation_memberships_unit_id_organisation_units"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_organisation_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_organisation_memberships")),
        sa.UniqueConstraint(
            "user_id",
            "unit_id",
            name=op.f("uq_user_organisation_memberships_user_id"),
        ),
    )
    with op.batch_alter_table("user_organisation_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_organisation_memberships_unit_id"),
            ["unit_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_organisation_memberships_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "request_route_selections",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 3",
            name=op.f("ck_request_route_selections_route_position_range"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_route_selections_request_id_service_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["organisation_units.id"],
            name=op.f("fk_request_route_selections_unit_id_organisation_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_route_selections")),
        sa.UniqueConstraint(
            "request_id",
            "position",
            name=op.f("uq_request_route_selections_request_id"),
        ),
    )
    with op.batch_alter_table("request_route_selections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_route_selections_request_id"),
            ["request_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_request_route_selections_unit_id"),
            ["unit_id"],
            unique=False,
        )

    op.create_table(
        "deliverables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "CHANGES_REQUIRED",
                "APPROVED",
                "RELEASED",
                name="deliverable_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("released_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("release_recipients", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_deliverables_approved_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_deliverables_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["released_by_user_id"],
            ["users.id"],
            name=op.f("fk_deliverables_released_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_deliverables_request_id_service_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliverables")),
        sa.UniqueConstraint(
            "request_id", "version", name=op.f("uq_deliverables_request_id")
        ),
    )
    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deliverables_request_id"), ["request_id"], unique=False
        )

    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_feedback_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_feedback_request_id_service_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["users.id"], name=op.f("fk_feedback_requester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_request_id"), ["request_id"], unique=True
        )

    op.create_table(
        "request_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "prior_status",
            sa.Enum(
                "ROUTING_PENDING",
                "TRIAGE_REVIEW",
                "INFORMATION_REQUIRED",
                "COORDINATION_REVIEW",
                "ON_HOLD",
                "ALLOCATION_REVIEW",
                "DELIVERY_PLANNING",
                "IN_PROGRESS",
                "LEAD_REVIEW",
                "REWORK_REQUIRED",
                "QUALITY_REVIEW",
                "READY_FOR_RELEASE",
                "COMPLETED",
                "CLOSED_NOT_PROGRESSED",
                "CANCELLED",
                name="event_prior_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "next_status",
            sa.Enum(
                "ROUTING_PENDING",
                "TRIAGE_REVIEW",
                "INFORMATION_REQUIRED",
                "COORDINATION_REVIEW",
                "ON_HOLD",
                "ALLOCATION_REVIEW",
                "DELIVERY_PLANNING",
                "IN_PROGRESS",
                "LEAD_REVIEW",
                "REWORK_REQUIRED",
                "QUALITY_REVIEW",
                "READY_FOR_RELEASE",
                "COMPLETED",
                "CLOSED_NOT_PROGRESSED",
                "CANCELLED",
                name="event_next_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_request_events_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_request_events_request_id_service_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_events")),
        sa.UniqueConstraint("event_hash", name="uq_request_events_event_hash"),
    )
    with op.batch_alter_table("request_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_request_events_request_created",
            ["request_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.String(length=160), nullable=False),
        sa.Column("process_definition_key", sa.String(length=128), nullable=True),
        sa.Column("process_version", sa.Integer(), nullable=True),
        sa.Column("process_instance_key", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "START_PENDING",
                "ACTIVE",
                "COMPLETED",
                "TERMINATED",
                "ERROR",
                name="workflow_instance_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("current_element_id", sa.String(length=160), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_workflow_instances_request_id_service_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_instances")),
        sa.UniqueConstraint(
            "process_instance_key",
            name=op.f("uq_workflow_instances_process_instance_key"),
        ),
    )
    with op.batch_alter_table("workflow_instances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_instances_request_id"), ["request_id"], unique=True
        )

    op.create_table(
        "workflow_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SENT",
                "FAILED",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_generation", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_workflow_outbox_request_id_service_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_outbox")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_workflow_outbox_idempotency_key")
        ),
    )
    with op.batch_alter_table("workflow_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_outbox_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_outbox_status"), ["status"], unique=False
        )

    op.create_table(
        "workflow_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_instance_id", sa.Uuid(), nullable=False),
        sa.Column("task_key", sa.String(length=128), nullable=False),
        sa.Column("element_id", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "candidate_role",
            sa.Enum(
                "PLATFORM_ADMIN",
                "REQUESTER",
                "INTAKE_TRIAGE",
                "SERVICE_COORDINATION",
                "OPERATIONS_ALLOCATION",
                "DELIVERY_TEAM_LEAD",
                "DELIVERY_SPECIALIST",
                "QUALITY_RELEASE",
                name="task_candidate_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "expected_status",
            sa.Enum(
                "ROUTING_PENDING",
                "TRIAGE_REVIEW",
                "INFORMATION_REQUIRED",
                "COORDINATION_REVIEW",
                "ON_HOLD",
                "ALLOCATION_REVIEW",
                "DELIVERY_PLANNING",
                "IN_PROGRESS",
                "LEAD_REVIEW",
                "REWORK_REQUIRED",
                "QUALITY_REVIEW",
                "READY_FOR_RELEASE",
                "COMPLETED",
                "CLOSED_NOT_PROGRESSED",
                "CANCELLED",
                name="task_expected_request_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLAIM_PENDING",
                "CLAIMED",
                "COMPLETION_PENDING",
                "COMPLETED",
                "CANCELLED",
                "ERROR",
                name="workflow_task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_workflow_tasks_assignee_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_workflow_tasks_request_id_service_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_instance_id"],
            ["workflow_instances.id"],
            name=op.f("fk_workflow_tasks_workflow_instance_id_workflow_instances"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_tasks")),
        sa.UniqueConstraint("task_key", name=op.f("uq_workflow_tasks_task_key")),
    )
    with op.batch_alter_table("workflow_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_tasks_element_id"), ["element_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_tasks_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workflow_tasks_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_tasks_request_id"))
        batch_op.drop_index(batch_op.f("ix_workflow_tasks_element_id"))

    op.drop_table("workflow_tasks")
    with op.batch_alter_table("workflow_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_outbox_status"))
        batch_op.drop_index(batch_op.f("ix_workflow_outbox_request_id"))

    op.drop_table("workflow_outbox")
    with op.batch_alter_table("workflow_instances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_instances_request_id"))

    op.drop_table("workflow_instances")
    with op.batch_alter_table("request_events", schema=None) as batch_op:
        batch_op.drop_index("ix_request_events_request_created")

    op.drop_table("request_events")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_request_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliverables_request_id"))

    op.drop_table("deliverables")
    with op.batch_alter_table("request_route_selections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_route_selections_unit_id"))
        batch_op.drop_index(batch_op.f("ix_request_route_selections_request_id"))

    op.drop_table("request_route_selections")
    with op.batch_alter_table("user_organisation_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_organisation_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_organisation_memberships_unit_id"))

    op.drop_table("user_organisation_memberships")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("service_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_requests_status"))
        batch_op.drop_index(batch_op.f("ix_service_requests_requester_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_reference"))
        batch_op.drop_index(batch_op.f("ix_service_requests_assigned_specialist_id"))
        batch_op.drop_index(batch_op.f("ix_service_requests_assigned_delivery_team"))

    op.drop_table("service_requests")
    with op.batch_alter_table("organisation_units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organisation_units_parent_id"))
        batch_op.drop_index(batch_op.f("ix_organisation_units_kind"))
        batch_op.drop_index(batch_op.f("ix_organisation_units_is_configured"))
        batch_op.drop_index(batch_op.f("ix_organisation_units_code"))

    op.drop_table("organisation_units")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))

    op.drop_table("users")
    # ### end Alembic commands ###
